apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: frigate
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  volumeName: frigate-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: frigate-config-pv
