apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-pv
  namespace: frigate
spec:
  storageClassName: nfs-client
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/frigate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
  namespace: frigate
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/config"
