apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-pv
  namespace: frigate
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 3000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
  namespace: frigate
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
